/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra un negocio nuevo
         * @description Crea el usuario, el negocio, el empleado dueño y la suscripción de prueba, y devuelve los tokens.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia sesión */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renueva el access token
         * @description Rota el refresh token: el que se envía queda revocado y se devuelve uno nuevo.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cierra la sesión
         * @description Revoca el refresh token enviado y toda su cadena de rotaciones. Es público a propósito: alcanza con presentar el refresh token, así se puede cerrar sesión aunque el access token ya haya vencido.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve el usuario, su negocio y su rol */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambia la contraseña
         * @description Cierra todas las sesiones abiertas del usuario.
         */
        patch: operations["AuthController_changePassword"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Devuelve el negocio del usuario logueado
         * @description Incluye el plan contratado y sus límites.
         */
        get: operations["TenantsController_findMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edita los datos del negocio
         * @description El `slug` no se edita acá: es la URL pública del portal de reservas.
         */
        patch: operations["TenantsController_updateMine"];
        trace?: never;
    };
    "/tenants/me/branding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve la personalización del portal público */
        get: operations["TenantsController_findBranding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edita la personalización del portal público
         * @description Los campos nullables se borran mandando `null`; omitirlos los deja como están.
         */
        patch: operations["TenantsController_updateBranding"];
        trace?: never;
    };
    "/tenants/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve la configuración operativa del negocio */
        get: operations["TenantsController_findSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edita la configuración operativa del negocio
         * @description Política de cancelación, seña obligatoria y buffer por defecto entre turnos.
         */
        patch: operations["TenantsController_updateSettings"];
        trace?: never;
    };
    "/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista las sucursales del negocio */
        get: operations["BranchesController_findAll"];
        put?: never;
        /**
         * Crea una sucursal con su horario semanal
         * @description Valida el límite de sucursales del plan. Si no se manda `businessHours`, la sucursal nace abierta de lunes a viernes de 09:00 a 18:00.
         */
        post: operations["BranchesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve una sucursal con su horario semanal */
        get: operations["BranchesController_findOne"];
        put?: never;
        post?: never;
        /**
         * Da de baja una sucursal
         * @description Baja lógica. Para sacarla de la agenda sin perder el historial, mejor desactivarla con `PATCH { isActive: false }`.
         */
        delete: operations["BranchesController_remove"];
        options?: never;
        head?: never;
        /**
         * Edita los datos de una sucursal
         * @description El horario NO se edita acá: va por `PUT /branches/:id/business-hours`.
         */
        patch: operations["BranchesController_update"];
        trace?: never;
    };
    "/branches/{id}/business-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve el horario semanal de la sucursal */
        get: operations["BranchesController_findBusinessHours"];
        /**
         * Reemplaza el horario semanal completo
         * @description Hay que mandar los 7 días. Un día con `isClosed: true` va sin horas; uno abierto necesita `opensAt` y `closesAt`, y tiene que cerrar después de abrir.
         */
        put: operations["BranchesController_setBusinessHours"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{id}/special-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista los días especiales de la sucursal
         * @description Feriados y jornadas con horario distinto al de la semana.
         */
        get: operations["BranchesController_findSpecialDays"];
        put?: never;
        /** Carga un feriado o una jornada especial */
        post: operations["BranchesController_createSpecialDay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/branches/{id}/special-days/{specialDayId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Borra un día especial */
        delete: operations["BranchesController_removeSpecialDay"];
        options?: never;
        head?: never;
        /**
         * Edita un día especial
         * @description La fecha no se edita: para moverlo de día, se borra y se carga de nuevo.
         */
        patch: operations["BranchesController_updateSpecialDay"];
        trace?: never;
    };
    "/employees/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activa la cuenta de un empleado invitado
         * @description Recibe el token del link de invitación y la contraseña elegida. Después de esto el empleado ya puede iniciar sesión normalmente.
         */
        post: operations["EmployeesController_activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista los empleados del negocio */
        get: operations["EmployeesController_findAll"];
        put?: never;
        /**
         * Invita a un empleado
         * @description Crea la cuenta sin contraseña y devuelve el link de activación, que se muestra **una sola vez**. Valida el límite de empleados del plan.
         */
        post: operations["EmployeesController_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve un empleado y sus sucursales */
        get: operations["EmployeesController_findOne"];
        put?: never;
        post?: never;
        /**
         * Da de baja a un empleado
         * @description Baja lógica. Para cortarle el acceso sin sacarlo del historial, mejor desactivarlo con `PATCH { isActive: false }`.
         */
        delete: operations["EmployeesController_remove"];
        options?: never;
        head?: never;
        /**
         * Edita el vínculo del empleado con el negocio
         * @description Rol, estado y datos laborales. Los datos personales (nombre, email) son de la cuenta del usuario y no se editan por acá.
         */
        patch: operations["EmployeesController_update"];
        trace?: never;
    };
    "/employees/{id}/invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reenvía la invitación
         * @description Emite un link nuevo y revoca el anterior. Solo mientras el empleado no haya activado su cuenta.
         */
        post: operations["EmployeesController_resendInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Define en qué sucursales trabaja
         * @description Reemplaza el set completo. Sacarle una sucursal borra también el horario que tuviera ahí.
         */
        put: operations["EmployeesController_setBranches"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve el horario semanal del empleado */
        get: operations["EmployeesController_findSchedules"];
        /**
         * Reemplaza el horario semanal completo
         * @description Un tramo por franja de trabajo: dos tramos el mismo día son un turno partido, y un día sin tramos es un día que no trabaja. Los tramos no se pueden pisar entre sí, ni siquiera en sucursales distintas.
         */
        put: operations["EmployeesController_setSchedules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/time-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista las ausencias del empleado
         * @description Con `from`/`to` devuelve las que se solapan con ese rango, no solo las que caen enteras adentro.
         */
        get: operations["EmployeesController_findTimeOff"];
        put?: never;
        /** Carga vacaciones o una ausencia */
        post: operations["EmployeesController_createTimeOff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employees/{id}/time-off/{timeOffId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Borra una ausencia */
        delete: operations["EmployeesController_removeTimeOff"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example ana@peluqueriaana.com */
            email: string;
            /**
             * @description Mínimo 8 caracteres, con al menos una letra y un número.
             * @example clave1234
             */
            password: string;
            /** @example Ana */
            firstName: string;
            /** @example Gómez */
            lastName: string;
            /** @example +54 9 11 5555-5555 */
            phone?: string;
            /**
             * @description Nombre del negocio. De acá sale el slug del tenant.
             * @example Peluquería Ana
             */
            businessName: string;
        };
        AuthTokensDto: {
            /** @description JWT de acceso. Va en el header Authorization. */
            accessToken: string;
            /** @description Token opaco para pedir un access token nuevo. Se rota en cada uso. */
            refreshToken: string;
            /** @example Bearer */
            tokenType: string;
            /**
             * @description Segundos de vida del access token.
             * @example 900
             */
            expiresIn: number;
        };
        LoginDto: {
            /** @example ana@peluqueriaana.com */
            email: string;
            /** @example clave1234 */
            password: string;
        };
        RefreshTokenDto: {
            /**
             * @description El refresh token tal cual lo devolvió login o refresh.
             * @example 4f0a1e2c-....7b.Zm9vYmFyYmF6
             */
            refreshToken: string;
        };
        MeUserDto: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            phone: string | null;
            /** Format: date-time */
            emailVerifiedAt: string | null;
        };
        MeTenantDto: {
            id: string;
            businessName: string;
            slug: string;
            timezone: string;
            currency: string;
            language: string;
            /** @enum {string} */
            subscriptionStatus: "TRIAL" | "ACTIVE" | "PAST_DUE" | "CANCELED" | "PAUSED";
            /** Format: date-time */
            trialEndsAt: string | null;
        };
        MeEmployeeDto: {
            id: string;
            /** @enum {string} */
            role: "OWNER" | "PROFESSIONAL" | "ADMINISTRATIVE";
            isOwner: boolean;
        };
        MeResponseDto: {
            user: components["schemas"]["MeUserDto"];
            tenant: components["schemas"]["MeTenantDto"];
            employee: components["schemas"]["MeEmployeeDto"];
        };
        ChangePasswordDto: {
            /** @example clave1234 */
            currentPassword: string;
            /**
             * @description Mínimo 8 caracteres, con al menos una letra y un número.
             * @example nuevaClave456
             */
            newPassword: string;
        };
        TenantPlanDto: {
            id: string;
            /** @example Básico */
            name: string;
            /** @example basico */
            slug: string;
            /** @description `null` = a medida / sin límite (plan Empresa). */
            maxEmployees: number | null;
            maxBranches: number | null;
            includesClinicRecords: boolean;
            includesResources: boolean;
            /** @enum {string} */
            supportLevel: "STANDARD" | "PRIORITY";
        };
        TenantResponseDto: {
            id: string;
            /** @example Peluquería Ana */
            businessName: string;
            /**
             * @description Identificador público del negocio (portal de reservas). Hoy no es editable.
             * @example peluqueria-ana
             */
            slug: string;
            /** @example America/Argentina/Buenos_Aires */
            timezone: string;
            /** @example ARS */
            currency: string;
            /** @example es */
            language: string;
            /** @enum {string} */
            subscriptionStatus: "TRIAL" | "ACTIVE" | "PAST_DUE" | "CANCELED" | "PAUSED";
            /** Format: date-time */
            trialEndsAt: string | null;
            plan: components["schemas"]["TenantPlanDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateTenantDto: {
            /** @example Peluquería Ana */
            businessName?: string;
            /**
             * @description Zona horaria IANA. Define cómo se muestran los turnos: en la base todo va en UTC.
             * @example America/Argentina/Buenos_Aires
             */
            timezone?: string;
            /**
             * @description Código ISO 4217.
             * @example ARS
             */
            currency?: string;
            /** @example es */
            language?: string;
        };
        TenantBrandingResponseDto: {
            id: string;
            logoUrl: string | null;
            /** @example #7C3AED */
            primaryColor: string | null;
            /** @example Peluquería Ana */
            displayName: string;
            description: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateTenantBrandingDto: {
            /**
             * @description URL del logo. `null` lo borra.
             * @example https://cdn.agendapp.com/logos/ana.png
             */
            logoUrl?: Record<string, never> | null;
            /**
             * @description Color principal en hexadecimal. `null` lo borra.
             * @example #7C3AED
             */
            primaryColor?: Record<string, never> | null;
            /** @example Peluquería Ana */
            displayName?: string;
            /**
             * @description Descripción del negocio para el portal. `null` la borra.
             * @example Cortes, color y peinados en Palermo.
             */
            description?: Record<string, never> | null;
        };
        TenantSettingsResponseDto: {
            id: string;
            /** @example 24 */
            cancellationPolicyHours: number;
            /** @enum {string} */
            cancellationRefundType: "FULL" | "PARTIAL" | "CREDIT" | "NONE";
            /** @example 50 */
            cancellationRefundPercentage: number | null;
            requireDepositForBooking: boolean;
            /** @example 0 */
            defaultBufferMinutes: number;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateTenantSettingsDto: {
            /**
             * @description Horas de anticipación con las que el cliente puede cancelar sin penalidad.
             * @example 24
             */
            cancellationPolicyHours?: number;
            /** @enum {string} */
            cancellationRefundType?: "FULL" | "PARTIAL" | "CREDIT" | "NONE";
            /**
             * @description Porcentaje a devolver. Obligatorio si el tipo de reembolso es `PARTIAL`; con cualquier otro tipo se guarda en `null`.
             * @example 50
             */
            cancellationRefundPercentage?: number;
            /** @description Si está en true, los turnos nacen en `pending_payment` hasta que se pague la seña. */
            requireDepositForBooking?: boolean;
            /**
             * @description Minutos de colchón entre turnos cuando el servicio no define uno.
             * @example 10
             */
            defaultBufferMinutes?: number;
        };
        BusinessHourDto: {
            /**
             * @description 0 = domingo, 6 = sábado.
             * @example 1
             */
            dayOfWeek: number;
            /**
             * @description Si es `true`, el día va sin horas: la sucursal no atiende.
             * @default false
             */
            isClosed: boolean;
            /** @example 09:00 */
            opensAt?: string;
            /** @example 18:00 */
            closesAt?: string;
        };
        CreateBranchDto: {
            /** @example Sucursal Centro */
            name: string;
            /** @example Av. Corrientes 1234 */
            address?: Record<string, never>;
            /** @example +54 11 5555-5555 */
            phone?: Record<string, never>;
            /** @description Los 7 días de la semana. Si se omite, la sucursal nace abierta de lunes a viernes de 09:00 a 18:00 y cerrada el fin de semana. */
            businessHours?: components["schemas"]["BusinessHourDto"][];
        };
        BusinessHourResponseDto: {
            /** @example 1 */
            dayOfWeek: number;
            isClosed: boolean;
            /** @example 09:00 */
            opensAt: string | null;
            /** @example 18:00 */
            closesAt: string | null;
        };
        BranchDetailResponseDto: {
            id: string;
            /** @example Sucursal Centro */
            name: string;
            /** @example Av. Corrientes 1234 */
            address: string | null;
            /** @example +54 11 5555-5555 */
            phone: string | null;
            /** @description Una sucursal inactiva no toma turnos, pero sigue existiendo. */
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            businessHours: components["schemas"]["BusinessHourResponseDto"][];
        };
        BranchResponseDto: {
            id: string;
            /** @example Sucursal Centro */
            name: string;
            /** @example Av. Corrientes 1234 */
            address: string | null;
            /** @example +54 11 5555-5555 */
            phone: string | null;
            /** @description Una sucursal inactiva no toma turnos, pero sigue existiendo. */
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateBranchDto: {
            /** @example Sucursal Centro */
            name?: string;
            /**
             * @description `null` borra la dirección.
             * @example Av. Corrientes 1234
             */
            address?: Record<string, never> | null;
            /**
             * @description `null` borra el teléfono.
             * @example +54 11 5555-5555
             */
            phone?: Record<string, never> | null;
            /** @description Desactivar una sucursal la saca de la agenda sin borrarla. */
            isActive?: boolean;
        };
        SetBusinessHoursDto: {
            /** @description Los 7 días de la semana, sin repetir ninguno. */
            days: components["schemas"]["BusinessHourDto"][];
        };
        SpecialDayResponseDto: {
            id: string;
            /** @example 2026-12-25 */
            date: string;
            /** @description `true` = feriado; `false` = horario especial. */
            isClosed: boolean;
            /** @example 10:00 */
            opensAt: string | null;
            /** @example 14:00 */
            closesAt: string | null;
            /** @example Navidad */
            description: string | null;
        };
        CreateSpecialDayDto: {
            /** @example 2026-12-25 */
            date: string;
            /**
             * @description Cerrado (feriado) por defecto. En `false` es una jornada con horario especial y exige `opensAt` y `closesAt`.
             * @default true
             */
            isClosed: boolean;
            /** @example 10:00 */
            opensAt?: string;
            /** @example 14:00 */
            closesAt?: string;
            /** @example Navidad */
            description?: Record<string, never>;
        };
        UpdateSpecialDayDto: {
            isClosed?: boolean;
            /** @example 10:00 */
            opensAt?: string;
            /** @example 14:00 */
            closesAt?: string;
            /**
             * @description `null` borra la descripción.
             * @example Navidad
             */
            description?: Record<string, never> | null;
        };
        ActivateEmployeeDto: {
            /** @description El token del link de invitación (`<id>.<secret>`). */
            token: string;
            /**
             * @description Mínimo 8 caracteres, con al menos una letra y un número.
             * @example clave1234
             */
            password: string;
        };
        InviteEmployeeDto: {
            /** @example ana@peluqueria.test */
            email: string;
            /** @example Ana */
            firstName: string;
            /** @example Gómez */
            lastName: string;
            /** @example +54 11 5555-5555 */
            phone?: Record<string, never>;
            /**
             * @description El rol `OWNER` no se asigna por acá.
             * @example PROFESSIONAL
             * @enum {string}
             */
            role: "PROFESSIONAL" | "ADMINISTRATIVE";
            /** @example 2026-03-01 */
            hiredAt?: Record<string, never>;
            /** @example Colorista, 10 años de experiencia. */
            bio?: Record<string, never>;
            /** @example https://cdn.agendapp.com/avatars/ana.png */
            avatarUrl?: Record<string, never>;
            /** @description Sucursales donde va a trabajar. Se pueden asignar después con `PUT /employees/:id/branches`. */
            branchIds?: string[];
        };
        EmployeeUserDto: {
            id: string;
            /** @example ana@peluqueria.test */
            email: string;
            /** @example Ana */
            firstName: string;
            /** @example Gómez */
            lastName: string;
            phone: string | null;
        };
        EmployeeResponseDto: {
            id: string;
            /** @enum {string} */
            role: "OWNER" | "PROFESSIONAL" | "ADMINISTRATIVE";
            isOwner: boolean;
            isActive: boolean;
            /**
             * @description `PENDING` mientras no aceptó la invitación: existe pero no puede entrar.
             * @enum {string}
             */
            status: "PENDING" | "ACTIVE";
            /** @example 2026-03-01 */
            hiredAt: string | null;
            bio: string | null;
            avatarUrl: string | null;
            user: components["schemas"]["EmployeeUserDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        EmployeeInvitationResponseDto: {
            employee: components["schemas"]["EmployeeResponseDto"];
            /**
             * @description Link de activación. **Se muestra una sola vez**: en la base queda solo su hash. Si se pierde, hay que reenviar la invitación.
             * @example http://localhost:3000/activar?token=<id>.<secret>
             */
            activationUrl: string;
            /**
             * Format: date-time
             * @description Cuándo deja de servir el link.
             */
            expiresAt: string;
        };
        EmployeeDetailResponseDto: {
            id: string;
            /** @enum {string} */
            role: "OWNER" | "PROFESSIONAL" | "ADMINISTRATIVE";
            isOwner: boolean;
            isActive: boolean;
            /**
             * @description `PENDING` mientras no aceptó la invitación: existe pero no puede entrar.
             * @enum {string}
             */
            status: "PENDING" | "ACTIVE";
            /** @example 2026-03-01 */
            hiredAt: string | null;
            bio: string | null;
            avatarUrl: string | null;
            user: components["schemas"]["EmployeeUserDto"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Ids de las sucursales donde trabaja. */
            branchIds: string[];
        };
        UpdateEmployeeDto: {
            /** @enum {string} */
            role?: "PROFESSIONAL" | "ADMINISTRATIVE";
            /** @description Desactivar corta el acceso en el acto, sin borrar nada. */
            isActive?: boolean;
            /** @example 2026-03-01 */
            hiredAt?: Record<string, never> | null;
            bio?: Record<string, never> | null;
            avatarUrl?: Record<string, never> | null;
        };
        SetEmployeeBranchesDto: {
            /** @description Set completo de sucursales donde trabaja. Un array vacío lo deja sin ninguna. */
            branchIds: string[];
        };
        EmployeeShiftResponseDto: {
            id: string;
            branchId: string;
            /** @example 1 */
            dayOfWeek: number;
            /** @example 09:00 */
            startsAt: string;
            /** @example 13:00 */
            endsAt: string;
        };
        EmployeeShiftDto: {
            /** @description Sucursal donde cubre este tramo. */
            branchId: string;
            /** @example 1 */
            dayOfWeek: number;
            /** @example 09:00 */
            startsAt: string;
            /** @example 13:00 */
            endsAt: string;
        };
        SetEmployeeSchedulesDto: {
            shifts: components["schemas"]["EmployeeShiftDto"][];
        };
        TimeOffResponseDto: {
            id: string;
            employeeId: string;
            /** @description `null` = en todas las sucursales. */
            branchId: string | null;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt: string;
            reason: string | null;
        };
        CreateTimeOffDto: {
            /** @description Sucursal donde no va a estar. `null` (o ausente) = en ninguna, que es el caso normal de unas vacaciones. */
            branchId?: Record<string, never> | null;
            /** @example 2026-01-05T09:00:00-03:00 */
            startsAt: string;
            /** @example 2026-01-20T09:00:00-03:00 */
            endsAt: string;
            /** @example Vacaciones */
            reason?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensDto"];
                };
            };
            /** @description El email ya está registrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensDto"];
                };
            };
            /** @description Credenciales inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensDto"];
                };
            };
            /** @description Refresh token inválido o vencido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La contraseña actual no es correcta */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    TenantsController_findMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_updateMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede editar el negocio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_findBranding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantBrandingResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El negocio no tiene branding cargado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_updateBranding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantBrandingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantBrandingResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede editar el branding */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_findSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSettingsResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El negocio no tiene configuración cargada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TenantsController_updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantSettingsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSettingsResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede editar la configuración */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_findAll: {
        parameters: {
            query?: {
                /** @description Filtra por estado. Si se omite, vienen todas. */
                isActive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResponseDto"][];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La sucursal no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBranchDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDetailResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede crear sucursales, o el plan llegó al límite */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La sucursal no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ya existe una sucursal con ese nombre */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDetailResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La sucursal no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sucursal dada de baja */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede dar de baja sucursales */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La sucursal no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBranchDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede editar sucursales */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La sucursal no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ya existe una sucursal con ese nombre */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_findBusinessHours: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessHourResponseDto"][];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La sucursal no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_setBusinessHours: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBusinessHoursDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessHourResponseDto"][];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede editar los horarios */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La sucursal no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_findSpecialDays: {
        parameters: {
            query?: {
                /** @description Desde (inclusive). */
                from?: string;
                /** @description Hasta (inclusive). */
                to?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialDayResponseDto"][];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La sucursal no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_createSpecialDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpecialDayDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialDayResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede cargar días especiales */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La sucursal no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Esa fecha ya tiene un día especial */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_removeSpecialDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                specialDayId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Día especial borrado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede borrar días especiales */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La sucursal no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BranchesController_updateSpecialDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                specialDayId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSpecialDayDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialDayResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede editar días especiales */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La sucursal no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateEmployeeDto"];
            };
        };
        responses: {
            /** @description Cuenta activada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El link no es válido, ya se usó o venció */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_findAll: {
        parameters: {
            query?: {
                /** @description Filtra por estado. Sin esto, vienen todos. */
                isActive?: boolean;
                role?: "OWNER" | "PROFESSIONAL" | "ADMINISTRATIVE";
                /** @description Solo los que trabajan en esta sucursal. */
                branchId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponseDto"][];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteEmployeeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeInvitationResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede invitar, o el plan llegó al límite */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ese email ya tiene una cuenta */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeDetailResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El empleado no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Empleado dado de baja */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede dar de baja, o el empleado es el dueño */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede editar empleados, o el empleado es el dueño */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El empleado no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_resendInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeInvitationResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El empleado no existe */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El empleado ya activó su cuenta */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_setBranches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEmployeeBranchesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Alguna sucursal no es de tu negocio */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede asignar sucursales */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_findSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeShiftResponseDto"][];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_setSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEmployeeSchedulesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeShiftResponseDto"][];
                };
            };
            /** @description Tramos superpuestos, mal formados o de una sucursal ajena */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede editar horarios */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_findTimeOff: {
        parameters: {
            query?: {
                /** @description Devuelve las ausencias que se solapan con [from, to]. */
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffResponseDto"][];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_createTimeOff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTimeOffDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeOffResponseDto"];
                };
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede cargar ausencias */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_removeTimeOff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                timeOffId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ausencia borrada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token ausente, vencido o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tu rol no puede borrar ausencias */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
